name: express-esi

services:
  varnish:
    image: varnish:7.4
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - node

  node:
    image: express-esi
    build:
      context: ../../
      target: express-prod
    user: node
    init: true
    command: ["node", "dist/server.js"]
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - REACT_ESI_SECRET=${REACT_ESI_SECRET:-ChangeMe}
    restart: unless-stopped
